require("gitsigns-settings")
require("lualine-settings")
require("lsp-settings")
require("telescope-settings")
require("lightbulb-settings")
require("nvim-tree-settings")
require("formatter-settings")
